In [ ]:
import tensorflow as tf     # 导入tensorflow

node1 = tf.constant([[3.0,1.5],[2.5,6.0]],tf.float32)  # 创建2个常量
node2 = tf.constant([[4.0,1.0],[5.0,2.5]],tf.float32)
node3 = tf.add(node1, node2)  # 定义加法运算

node3


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7. , 2.5],
       [7.5, 8.5]], dtype=float32)>

In [5]:
print(node3.numpy())  # 输出运算结果Tensor的值

[[7.  2.5]
 [7.5 8.5]]


In [9]:
print(node3.numpy())  # 输出[[7.  2.5]
                      #     [7.5 8.5]]
print(node3.shape)    # 输出(2, 2)，即矩阵的长和宽均为2
print(node3.dtype)    # 输出 <dtype: 'float32'>

[[7.  2.5]
 [7.5 8.5]]
(2, 2)
<dtype: 'float32'>


In [11]:
scalar = tf.constant(100)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
cube_matrix = tf.constant([[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]])

print(scalar.shape)             # 输出 ()
print(vector.shape)             # 输出 (5,)
print(matrix.shape)             # 输出 (2, 3)
print(cube_matrix.get_shape())  # 输出 (3, 3, 1)

()
(5,)
(2, 3)
(3, 3, 1)


In [3]:
a = tf.constant([1, 2])
b = tf.constant([2.0, 3.0])

result = tf.add(a,b)   # 运行报错

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [16]:
hello = tf.constant("Hello, World!",tf.string)

In [17]:
hello

<tf.Tensor: id=23, shape=(), dtype=string, numpy=b'Hello, World!'>

In [20]:
a = tf.constant([1, 2])
b = tf.constant([2.0, 3.0])

a = tf.cast(a,tf.float32)  # 数据类型转换

result = tf.add(a,b)
result

<tf.Tensor: id=34, shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>

In [7]:
a = tf.constant([1, 2])
a

<tf.Tensor: id=9, shape=(2,), dtype=int32, numpy=array([1, 2])>

In [8]:
b = tf.constant([3, 4],tf.float32)
b

<tf.Tensor: id=10, shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [9]:
c = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) 
c

<tf.Tensor: id=13, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
v1 = tf.Variable([1, 2])
v2 = tf.Variable([3, 4],tf.float32)
v1,v2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>)

In [16]:
c = tf.constant(1)
v = tf.Variable(c)
c,v

(<tf.Tensor: id=57, shape=(), dtype=int32, numpy=1>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>)

In [19]:
v = v1

In [20]:
v

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [24]:
v = tf.Variable(5)
v.assign(v+1)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

In [26]:
v1 = tf.Variable(5)
v2 = tf.Variable(5)
v1.assign_add(1)
v2.assign_sub(1)
v1,v2

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>)

In [7]:
v1 = tf.Variable(0)
for i in range(11):
    v1.assign_add(i)
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=55>