In [1]:
# 在TensorFlow 2下执行TensorFlow 1.x版本代码
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()     # 改为图执行模式运行

In [2]:
# 定义了一个简单的“计算图”
node1 = tf.constant(3.0,tf.float32,name="node1")
node2 = tf.constant(4.0,tf.float32,name="node2")
node3 = tf.add(node1, node2)

print(node3)

Tensor("Add:0", shape=(), dtype=float32)


In [3]:
node1,node2,node3

(<tf.Tensor 'node1:0' shape=() dtype=float32>,
 <tf.Tensor 'node2:0' shape=() dtype=float32>,
 <tf.Tensor 'Add:0' shape=() dtype=float32>)

In [5]:
sess = tf.Session()    # 建立对话并显示运行结果

print("运行sess.run(node1)的结果：", sess.run(node1))
print("运行sess.run(node2)的结果：", sess.run(node2))
print("运行sess.run(node3)的结果：", sess.run(node3))

sess.close()     # 关闭session

运行sess.run(node1)的结果： 3.0
运行sess.run(node2)的结果： 4.0
运行sess.run(node3)的结果： 7.0


In [6]:
tens1 = tf.constant([1,2,3])    # 定义计算图
sess = tf.Session()    # 创建一个会话

#使用这个创建好的会话来得到关心的运算的结果。比如可以调用 sess.run(tens1)
print(sess.run(tens1))    # 输出结果应该为 [1 2 3]

sess.close()    #关闭会话使得本次运行中使用到的资源可以被释放

[1 2 3]


In [7]:
tens1 = tf.constant([1,2,3]) 

sess = tf.Session()
try:
    print(sess.run(tens1))
except:
    print("Exception!")
finally:
    sess.close()    #确保能关闭会话

[1 2 3]


In [8]:
tens1 = tf.constant([1,2,3]) 

#创建一个会话，并通过Python中的上下文管理器来管理这个会话
with tf.Session() as sess:
    print(sess.run(tens1))

# 不需要再调用 Session.close() 函数来关闭会话
# 当上下文退出时会话关闭和资源释放也自动完成了

[1 2 3]


In [11]:
tens1 = tf.constant([1,2,3]) 

sess = tf.Session()
with sess.as_default():
    print(tens1.eval())

[1 2 3]


In [12]:
tens1 = tf.constant([1,2,3]) 
sess = tf.Session()

#下面两个命令有相同的功能
print(sess.run(tens1))
print(tens1.eval(session=sess))

NameError: name 'result' is not defined

In [10]:
tens1 = tf.constant([1,2,3]) 

sess = tf.InteractiveSession()

print(tens1.eval())

[1 2 3]


In [ ]:
node1 = tf.Variable(3.0,tf.float32,name="node1")
node2 = tf.Variable(4.0,tf.float32,name="node2")
result = tf.add(node1, node2)

sess = tf.Session()

node1_init = node1.initializer    # 定义单个变量初始化操作
node2_init = node2.initializer

sess.run(node1_init)    # 运行单个变量初始化操作
sess.run(node2_init)

print(sess.run(result))

7.0


In [ ]:
node1 = tf.Variable(3.0,tf.float32,name="node1")
node2 = tf.Variable(4.0,tf.float32,name="node2")
result = tf.add(node1, node2)

sess = tf.Session()

init = tf.global_variables_initializer()    #定义变量初始化操作
sess.run(init)    #必须先运行这个初始化操作

print(sess.run(result))


7.0


In [ ]:
# 在TensorFlow 2下执行TensorFlow 1.x版本代码
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()     # 改为图执行模式运行

a = tf.placeholder(tf.float32, name='a')
b = tf.placeholder(tf.float32, name='b')
c = a+b    # 作用和tf.add(a,b)一样，TensorFlow重载了运算符

a_value = float(input("a = "))  # 从终端读入一个浮点数并放入变量a_
b_value = float(input("b = "))

with tf.Session() as sess:
    # 通过feed_dict的参数传值，按字典格式
    result = sess.run(c, feed_dict={a:a_value, b:b_value})  
    print(result)

a = 5.0
b = 3.5
8.5


In [ ]:
# 在TensorFlow 2下执行TensorFlow 1.x版本代码
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()     # 改为图执行模式运行

a = tf.placeholder(tf.float32, name='a')
b = tf.placeholder(tf.float32, name='b')
c = tf.multiply(a, b, name='c')
d = tf.subtract(a, b, name='d')

with tf.Session() as sess:
    #两个操作涉及的占位符一次性Feed，返回的两个值分别赋给两个变量
    rc,rd = sess.run([c,d], feed_dict={a:[8.0,2.0,3.5], b:[1.5,2.0,4.]})
    print("value of c=",rc,"value of d=",rd)

value of c= [12.  4. 14.] value of d= [ 6.5  0.  -0.5]


In [ ]:
# 在TensorFlow 2下执行TensorFlow 1.x版本代码
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()     # 改为图执行模式运行

a = tf.placeholder(tf.float32, name='a')
b = tf.placeholder(tf.float32, name='b')
c = tf.multiply(a, b, name='c')
d = tf.subtract(a, b, name='d')

with tf.Session() as sess:
    #两个操作涉及的占位符一次性Feed，返回的两个值分别赋给两个变量
    x = sess.run([c,d], feed_dict={a:[8.0,2.0,3.5], b:[1.5,2.0,4.]})
    print(x,type(x))

(array([12.,  4., 14.], dtype=float32), array([ 6.5,  0. , -0.5], dtype=float32)) <class 'tuple'>


In [6]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
# tf.reset_default_graph()
value = tf.Variable(0,name='value')
res = tf.Variable(0,name='res')
one = tf.constant(1)
new_value = tf.add(value,one)
update_value = tf.assign(value,new_value)
temp_value = tf.add(res,value)
update_res_value = tf.assign(res,temp_value)
# log_dir = 'log/'
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for _ in range(10):
        sess.run(update_value)
        sess.run(update_res_value)
    print(sess.run(res))

# writer = tf.summary.FileWriter(log_dir,sess.graph)


55
