In [2]:
import numpy as np

#设置随机数种子

np.random.seed(5)

In [3]:
#生成生成[0,1)之间随机浮点数

np.random.rand()  

0.22199317108973948

In [4]:
#生成一个形状为5的一维数组

np.random.rand(5)  

array([ 0.87073231,  0.20671916,  0.91861091,  0.48841119,  0.61174386])

In [5]:
#生成2x3的二维数组

np.random.rand(2,3) 

array([[ 0.76590786,  0.51841799,  0.2968005 ],
       [ 0.18772123,  0.08074127,  0.7384403 ]])

In [8]:
# numpy.random.randn(d0, d1, …, dn) 是从标准正态分布中返回一个或多个样本值
# 标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N（0，1）

np.random.randn(20)

array([ 1.45073354,  0.60687032, -0.37562084, -1.42192455, -1.7811513 ,
       -0.74790579, -0.36840953, -2.24911813, -1.69367504,  0.30364847,
       -0.40899234, -0.75483059, -0.40751917, -0.81262476,  0.92751621,
        1.63995407,  2.07361553,  0.70979786,  0.74715259,  1.46309548])

In [10]:
np.random.randn(20,4)

array([[ 1.73844881,  1.46520488,  1.21228341, -0.6346525 ],
       [-1.5996985 ,  0.87715281, -0.09383245, -0.05567103],
       [-0.88942073, -1.30095145,  1.40216662,  0.46510099],
       [-1.06503262,  0.39042061,  0.30560017,  0.52184949],
       [ 2.23327081, -0.0347021 , -1.27962318,  0.03654264],
       [-0.64635659,  0.54856784,  0.21054246,  0.34650175],
       [-0.56705117,  0.41367881, -0.51025606,  0.51725935],
       [-0.30100513, -1.11840643,  0.49852362, -0.70609387],
       [ 1.4438811 ,  0.44295626,  0.46770521,  0.10134479],
       [-0.05935198, -2.38669774,  1.22217056, -0.81391201],
       [ 0.95626186, -0.63851056, -0.14312642, -0.22418983],
       [-1.03849524, -0.17170905,  0.47634618, -0.41417827],
       [-1.26408334, -0.57321556,  0.24981732,  1.14720208],
       [ 0.83594396,  0.28740365, -0.9955963 ,  0.90688947],
       [ 0.02421074, -0.23998173,  0.91011056,  0.61784475],
       [ 0.49961804, -1.15154425, -0.6105164 , -1.70388541],
       [ 0.19443738,  0.

In [11]:
'''numpy.random.standard_normal(size=None)：
   生产一个浮点数或N维浮点数组，取数范围：标准正态分布随机样本'''

np.random.standard_normal([2,3])

array([[-0.12253009, -0.8077431 , -0.23255622],
       [ 1.33515034, -0.44645673, -0.04978868]])

In [12]:
'''numpy.random.randint(low, high=None, size=None, dtype='l')：
  生成一个整数或N维整数数组，取数范围：若high不为None时，取[low,high)之间随机整数，
  否则取值[0,low)之间随机整数 '''

np.random.randint(1,100,5)

array([58, 34, 54, 97,  2])

In [13]:
np.random.randint(50,size=5)

array([ 6, 26, 14, 17, 26])